name: Run Python Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # Runs daily at 1 AM UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python SNBReportsAutomation.py
